/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Producer } from "./Producer";
import { ProducerCountArgs } from "./ProducerCountArgs";
import { ProducerFindManyArgs } from "./ProducerFindManyArgs";
import { ProducerFindUniqueArgs } from "./ProducerFindUniqueArgs";
import { CreateProducerArgs } from "./CreateProducerArgs";
import { UpdateProducerArgs } from "./UpdateProducerArgs";
import { DeleteProducerArgs } from "./DeleteProducerArgs";
import { ProducerService } from "../producer.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Producer)
export class ProducerResolverBase {
  constructor(
    protected readonly service: ProducerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Producer",
    action: "read",
    possession: "any",
  })
  async _producersMeta(
    @graphql.Args() args: ProducerCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Producer])
  @nestAccessControl.UseRoles({
    resource: "Producer",
    action: "read",
    possession: "any",
  })
  async producers(
    @graphql.Args() args: ProducerFindManyArgs
  ): Promise<Producer[]> {
    return this.service.producers(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Producer, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Producer",
    action: "read",
    possession: "own",
  })
  async producer(
    @graphql.Args() args: ProducerFindUniqueArgs
  ): Promise<Producer | null> {
    const result = await this.service.producer(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Producer)
  @nestAccessControl.UseRoles({
    resource: "Producer",
    action: "create",
    possession: "any",
  })
  async createProducer(
    @graphql.Args() args: CreateProducerArgs
  ): Promise<Producer> {
    return await this.service.createProducer({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Producer)
  @nestAccessControl.UseRoles({
    resource: "Producer",
    action: "update",
    possession: "any",
  })
  async updateProducer(
    @graphql.Args() args: UpdateProducerArgs
  ): Promise<Producer | null> {
    try {
      return await this.service.updateProducer({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Producer)
  @nestAccessControl.UseRoles({
    resource: "Producer",
    action: "delete",
    possession: "any",
  })
  async deleteProducer(
    @graphql.Args() args: DeleteProducerArgs
  ): Promise<Producer | null> {
    try {
      return await this.service.deleteProducer(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
